name: Data Exploration and Preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  data-exploration:
    runs-on: ubuntu-latest
    
    steps:
      # Krok 1: Sprawdzenie repozytorium
      - name: Checkout code
        uses: actions/checkout@v2

      # Krok 2: Ustawienie środowiska Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Krok 3: Instalacja zależności
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Krok 4: Uruchomienie skryptu
      - name: Run data exploration script
        run: |
          python main.py

      # Krok 5: Sprawdzanie wyników
      - name: Check if files were created
        run: |
          ls -alh
